from graphene import ObjectType, String, Float, Int, List, Field, Mutation, Schema, Boolean
from models import Coupon, db
from datetime import datetime, timedelta
import requests
import os
import traceback
import uuid 

# Add missing imports for HTTP requests and error handling
try:
    import urllib3
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
except ImportError:
    pass

class CouponType(ObjectType):
    id = Int()
    code = String()
    name = String()
    discountPercentage = Float()
    validUntil = String()
    isActive = Boolean()
    createdAt = String()
    updatedAt = String()
    # Tambahkan field yang hilang
    isAutoGenerated = Boolean()
    usedByUserId = Int()

    def resolve_discountPercentage(self, info):
        return self.discount_percentage
    
    def resolve_validUntil(self, info):
        if hasattr(self, 'valid_until') and self.valid_until:
            return self.valid_until.strftime('%Y-%m-%d %H:%M:%S')
        return None
    
    def resolve_isActive(self, info):
        return self.is_active
    
    def resolve_createdAt(self, info):
        if hasattr(self, 'created_at') and self.created_at:
            return self.created_at.strftime('%Y-%m-%d %H:%M:%S')
        return None
    
    def resolve_updatedAt(self, info):
        if hasattr(self, 'updated_at') and self.updated_at:
            return self.updated_at.strftime('%Y-%m-%d %H:%M:%S')
        return None
    
    # Tambahkan resolver untuk field baru
    def resolve_isAutoGenerated(self, info):
        return getattr(self, 'is_auto_generated', False)
    
    def resolve_usedByUserId(self, info):
        return getattr(self, 'used_by_user_id', None)
    
class CreateCouponResponse(ObjectType):
    coupon = Field(CouponType)
    success = Boolean()
    message = String()

class UseCouponResponse(ObjectType):
    success = Boolean()
    message = String()
    discount_amount = Float()

class TokenVerificationResponse(ObjectType):
    valid = Boolean()
    userId = Int()  # Changed from user_id to userId to match GraphQL conventions
    role = String()
    error = String()

class Query(ObjectType):
    coupons = List(CouponType)
    availableCoupons = List(CouponType)  # ← This should match gateway expectation
    coupon = Field(CouponType, id=Int(required=True))
    validate_coupon = Field(Boolean, code=String(required=True))

    def resolve_coupons(self, info):
        try:
            return Coupon.query.all()
        except Exception as e:
            print(f"Error in resolve_coupons: {str(e)}")
            traceback.print_exc()
            return []

    def resolve_availableCoupons(self, info):  # ← This should match the field name
        try:
            return Coupon.query.filter(
                Coupon.is_active == True,
                Coupon.valid_until >= datetime.utcnow()
            ).all()
        except Exception as e:
            print(f"Error in resolve_available_coupons: {str(e)}")
            traceback.print_exc()
            return []

    def resolve_coupon(self, info, id):
        try:
            return Coupon.query.get(id)
        except Exception as e:
            print(f"Error in resolve_coupon: {str(e)}")
            return None

    def resolve_validate_coupon(self, info, code):
        try:
            coupon = Coupon.query.filter_by(code=code).first()
            if not coupon:
                return False
            return coupon.is_active and coupon.valid_until >= datetime.utcnow()
        except Exception as e:
            print(f"Error in resolve_validate_coupon: {str(e)}")
            return False

class CreateCoupon(Mutation):
    class Arguments:
        code = String(required=True)
        name = String(required=True)
        discount_percentage = Float(required=True)
        valid_until = String(required=True)

    Output = CreateCouponResponse

    def mutate(self, info, code, name, discount_percentage, valid_until):
        try:
            # Check if coupon code already exists
            existing_coupon = Coupon.query.filter_by(code=code).first()
            if existing_coupon:
                return CreateCouponResponse(
                    coupon=None,
                    success=False,
                    message="Coupon code already exists"
                )

            # Parse date
            try:
                valid_until_date = datetime.strptime(valid_until, '%Y-%m-%d %H:%M:%S')
            except ValueError:
                try:
                    valid_until_date = datetime.strptime(valid_until, '%Y-%m-%d')
                except ValueError:
                    return CreateCouponResponse(
                        coupon=None,
                        success=False,
                        message="Invalid date format. Use YYYY-MM-DD or YYYY-MM-DD HH:MM:SS"
                    )

            # Create coupon
            coupon = Coupon(
                code=code,
                name=name,
                discount_percentage=discount_percentage,
                valid_until=valid_until_date,
                is_active=True
            )
            coupon.save()

            return CreateCouponResponse(
                coupon=coupon,
                success=True,
                message="Coupon created successfully"
            )
        except Exception as e:
            db.session.rollback()
            traceback.print_exc()
            return CreateCouponResponse(
                coupon=None,
                success=False,
                message=f"Error creating coupon: {str(e)}"
            )

class UseCoupon(Mutation):
    class Arguments:
        code = String(required=True)
        booking_amount = Float(required=True)

    Output = UseCouponResponse

    def mutate(self, info, code, booking_amount):
        try:
            print(f"DEBUG: UseCoupon mutation called with code: {code}, amount: {booking_amount}")
            
            coupon = Coupon.query.filter_by(code=code).first()
            
            if not coupon:
                print(f"DEBUG: Coupon not found with code: {code}")
                return UseCouponResponse(
                    success=False,
                    message="Coupon not found",
                    discount_amount=0.0
                )

            print(f"DEBUG: Found coupon: {coupon.code}, active: {coupon.is_active}, expires: {coupon.valid_until}")

            if not coupon.is_active:
                print(f"DEBUG: Coupon is not active")
                return UseCouponResponse(
                    success=False,
                    message="Coupon is not active",
                    discount_amount=0.0
                )

            if coupon.valid_until < datetime.utcnow():
                print(f"DEBUG: Coupon has expired")
                return UseCouponResponse(
                    success=False,
                    message="Coupon has expired",
                    discount_amount=0.0
                )

            # FIXED: Check if coupon has already been used
            if coupon.used_by_user_id is not None:
                print(f"DEBUG: Coupon already used by user: {coupon.used_by_user_id}")
                return UseCouponResponse(
                    success=False,
                    message="Coupon has already been used",
                    discount_amount=0.0
                )

            # Calculate discount
            discount_amount = booking_amount * (coupon.discount_percentage / 100)
            print(f"DEBUG: Calculated discount: {discount_amount} ({coupon.discount_percentage}%)")

            # IMPORTANT: DO NOT mark coupon as used here in validation-only mode
            # The coupon should only be marked as used when payment is actually completed
            # For now, just return the discount amount for preview

            return UseCouponResponse(
                success=True,
                message=f"Coupon applied successfully. {coupon.discount_percentage}% discount ({discount_amount:.2f} off)",
                discount_amount=discount_amount
            )
        except Exception as e:
            print(f"DEBUG: Exception in UseCoupon mutation: {str(e)}")
            traceback.print_exc()
            return UseCouponResponse(
                success=False,
                message=f"Error applying coupon: {str(e)}",
                discount_amount=0.0
            )

class MarkCouponUsed(Mutation):
    class Arguments:
        code = String(required=True)
        user_id = Int(required=True)

    Output = UseCouponResponse

    def mutate(self, info, code, user_id):
        try:
            print(f"DEBUG: MarkCouponUsed called with code: {code}, user_id: {user_id}")
            
            coupon = Coupon.query.filter_by(code=code).first()
            
            if not coupon:
                return UseCouponResponse(
                    success=False,
                    message="Coupon not found",
                    discount_amount=0.0
                )

            if not coupon.is_active:
                return UseCouponResponse(
                    success=False,
                    message="Coupon is not active",
                    discount_amount=0.0
                )

            if coupon.valid_until < datetime.utcnow():
                return UseCouponResponse(
                    success=False,
                    message="Coupon has expired",
                    discount_amount=0.0
                )

            if coupon.used_by_user_id is not None:
                return UseCouponResponse(
                    success=False,
                    message="Coupon has already been used",
                    discount_amount=0.0
                )

            # Mark coupon as used
            coupon.used_by_user_id = user_id
            coupon.is_active = False
            coupon.save()

            print(f"DEBUG: Coupon {code} marked as used by user {user_id}")

            return UseCouponResponse(
                success=True,
                message=f"Coupon {code} has been used successfully",
                discount_amount=coupon.discount_percentage
            )
        except Exception as e:
            print(f"DEBUG: Exception in MarkCouponUsed: {str(e)}")
            db.session.rollback()
            traceback.print_exc()
            return UseCouponResponse(
                success=False,
                message=f"Error marking coupon as used: {str(e)}",
                discount_amount=0.0
            )
            
class GenerateLoyaltyCoupon(Mutation):
    class Arguments:
        userId = Int(required=True)  # FIXED: Match gateway parameter name
        bookingCount = Int(required=True)  # FIXED: Match gateway parameter name

    Output = CreateCouponResponse

    def mutate(self, info, userId, bookingCount):  # FIXED: Match gateway parameter names
        try:
            # UPDATED: Generate loyalty coupon dengan logic baru
            if bookingCount < 3:
                return CreateCouponResponse(
                    coupon=None,
                    success=False,
                    message="Minimum 3 payments required for loyalty coupon"
                )
            
            # Calculate discount berdasarkan aturan baru:
            # Payment 3: 10%, Payment 7: 14%, Payment 11: 18%, dst (naik 4%)
            if bookingCount == 3:
                discount = 10.0
                tier = "Silver"
            else:
                # Setiap 4 payment setelah payment ke-3, naik 4%
                additional_milestones = (bookingCount - 3) // 4
                discount = 10.0 + (additional_milestones * 4.0)
                # Cap maximum discount at 30%
                discount = min(discount, 30.0)
                
                if discount >= 20:
                    tier = "Platinum"
                elif discount >= 15:
                    tier = "Gold" 
                else:
                    tier = "Silver"

            # FIXED: Generate unique coupon code using uuid instead of static method
            import uuid
            random_suffix = str(uuid.uuid4())[:8].upper()
            coupon_code = f"LOYALTY{userId}_{bookingCount}_{random_suffix}"
            coupon_name = f"{tier} Loyalty Coupon - {discount}% Discount"

            # Set expiry to 30 days from now
            from datetime import datetime, timedelta
            expiry_date = datetime.utcnow() + timedelta(days=30)

            coupon = Coupon(
                code=coupon_code,
                name=coupon_name,
                discount_percentage=discount,
                valid_until=expiry_date,
                is_active=True,
                is_auto_generated=True  # Mark as auto-generated
            )
            coupon.save()

            return CreateCouponResponse(
                coupon=coupon,
                success=True,
                message=f"{tier} loyalty coupon generated! {discount}% discount for {bookingCount} payments"
            )
        except Exception as e:
            db.session.rollback()
            import traceback
            traceback.print_exc()
            return CreateCouponResponse(
                coupon=None,
                success=False,
                message=f"Error generating loyalty coupon: {str(e)}"
            )
            
class UpdateCoupon(Mutation):
    class Arguments:
        id = Int(required=True)
        name = String()
        discount_percentage = Float()
        valid_until = String()
        is_active = Boolean()

    coupon = Field(CouponType)

    def mutate(self, info, id, name=None, discount_percentage=None, valid_until=None, is_active=None):
        try:
            coupon = Coupon.query.get(id)
            if not coupon:
                raise Exception(f"Coupon with ID {id} not found")

            if name:
                coupon.name = name
            if discount_percentage is not None:
                coupon.discount_percentage = discount_percentage
            if valid_until:
                try:
                    coupon.valid_until = datetime.strptime(valid_until, '%Y-%m-%d %H:%M:%S')
                except ValueError:
                    coupon.valid_until = datetime.strptime(valid_until, '%Y-%m-%d')
            if is_active is not None:
                coupon.is_active = is_active

            coupon.save()
            return UpdateCoupon(coupon=coupon)
        except Exception as e:
            db.session.rollback()
            traceback.print_exc()
            raise Exception(f"Error updating coupon: {str(e)}")

class DeleteCouponResponse(ObjectType):
    success = Boolean()
    message = String()

class DeleteCoupon(Mutation):
    class Arguments:
        id = Int(required=True)

    Output = DeleteCouponResponse

    def mutate(self, info, id):
        try:
            coupon = Coupon.query.get(id)
            if not coupon:
                return DeleteCouponResponse(
                    success=False,
                    message=f"Coupon with ID {id} not found"
                )

            coupon.delete()
            return DeleteCouponResponse(
                success=True,
                message=f"Coupon with ID {id} deleted successfully"
            )
        except Exception as e:
            db.session.rollback()
            traceback.print_exc()
            return DeleteCouponResponse(
                success=False,
                message=f"Error deleting coupon: {str(e)}"
            )

class VerifyToken(Mutation):
    class Arguments:
        token = String(required=True)

    Output = TokenVerificationResponse

    def mutate(self, info, token):
        try:
            print(f"Verifying token: {token[:20]}...")  # Debug log (show only first 20 chars)
            
            result = verify_token(token)
            if result['valid']:
                print(f"Token valid for user_id: {result['user_id']}, role: {result['role']}")  # Debug log
                return TokenVerificationResponse(
                    valid=True,
                    userId=result['user_id'],  # Changed to userId
                    role=result['role']
                )
            else:
                print(f"Token invalid: {result.get('error', 'Unknown error')}")  # Debug log
                return TokenVerificationResponse(
                    valid=False,
                    error=result.get('error', 'Invalid token')
                )
        except Exception as e:
            print(f"Token verification error: {str(e)}")  # Debug log
            traceback.print_exc()
            return TokenVerificationResponse(
                valid=False,
                error=f"Token verification failed: {str(e)}"
            )

    def resolve_verify_token(self, info, token):
        try:
            print(f"Resolving verify_token query")  # Debug log
            result = verify_token(token)
            if result['valid']:
                return TokenVerificationResponse(
                    valid=True,
                    userId=result['user_id'],  # Changed to userId
                    role=result['role']
                )
            else:
                return TokenVerificationResponse(
                    valid=False,
                    error=result.get('error', 'Invalid token')
                )
        except Exception as e:
            print(f"Error in resolve_verify_token: {str(e)}")  # Debug log
            traceback.print_exc()
            return TokenVerificationResponse(
                valid=False,
                error=f"Token verification failed: {str(e)}"
            )

class Mutation(ObjectType):
    create_coupon = CreateCoupon.Field()
    use_coupon = UseCoupon.Field()
    mark_coupon_used = MarkCouponUsed.Field()
    generate_loyalty_coupon = GenerateLoyaltyCoupon.Field()
    update_coupon = UpdateCoupon.Field()
    delete_coupon = DeleteCoupon.Field()
    verify_token = VerifyToken.Field()

schema = Schema(query=Query, mutation=Mutation)